<?php

return [

    'kantor' => [

        [
            'id' => 1,
            'nama' => 'Kantor Pusat PT BPR NTB PERSERODA',
            'alamat' => 'Kota Mataram, Nusa Tenggara Barat',
            'latitude' => -8.565730445185917,
            'longitude' => 116.07849753374737,
        ],
        [
            'id' => 2,
            'nama' => 'PT BPR NTB PERSERODA KPOKP',
            'alamat' => 'Kota Mataram, Nusa Tenggara Barat',
            'latitude' => -8.566038110783627,
            'longitude' => 116.07849552208928,
        ],

        // ================= LOMBOK BARAT & UTARA =================
        [
            'id' => 3,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Gerung',
            'alamat' => 'Gerung, Lombok Barat, NTB',
            'latitude' => -8.6847657,
            'longitude' => 116.1242950,
        ],
        [
            'id' => 4,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Narmada',
            'alamat' => 'Narmada, Lombok Barat, NTB',
            'latitude' => -8.5959348,
            'longitude' => 116.2008912,
        ],
        [
            'id' => 5,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Labuapi',
            'alamat' => 'Labuapi, Lombok Barat, NTB',
            'latitude' => -8.6341938,
            'longitude' => 116.0946244,
        ],
        [
            'id' => 6,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kuripan',
            'alamat' => 'Kuripan, Lombok Barat, NTB',
            'latitude' => -8.6612032,
            'longitude' => 116.1588660,
        ],
        [
            'id' => 7,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Gunung Sari',
            'alamat' => 'Gunung Sari, Lombok Barat, NTB',
            'latitude' => -8.542477,
            'longitude' => 116.105307,
        ],
        [
            'id' => 8,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kayangan',
            'alamat' => 'Kayangan, Lombok Utara, NTB',
            'latitude' => -8.256854,
            'longitude' => 116.257468,
        ],
        [
            'id' => 9,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Bayan',
            'alamat' => 'Bayan, Lombok Utara, NTB',
            'latitude' => -8.229135300382945,
            'longitude' => 116.42039019876431,
        ],

        // ================= LOMBOK TENGAH & TIMUR =================
        [
            'id' => 10,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Praya',
            'alamat' => 'Praya, Lombok Tengah, NTB',
            'latitude' => -8.703983,
            'longitude' => 116.266885,
        ],
        [
            'id' => 11,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Praya Timur',
            'alamat' => 'Praya Timur, Lombok Tengah, NTB',
            'latitude' => -8.762328,
            'longitude' => 116.351488,
        ],
        [
            'id' => 12,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Janapria',
            'alamat' => 'Janapria, Lombok Tengah, NTB',
            'latitude' => -8.697101,
            'longitude' => 116.403701,
        ],
        [
            'id' => 13,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Batukliang',
            'alamat' => 'Batukliang, Lombok Tengah, NTB',
            'latitude' => -8.624447,
            'longitude' => 116.309078,
        ],
        [
            'id' => 14,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Pujut',
            'alamat' => 'Pujut, Lombok Tengah, NTB',
            'latitude' => -8.80812,
            'longitude' => 116.295388,
        ],
        [
            'id' => 15,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Jonggat',
            'alamat' => 'Jonggat, Lombok Tengah, NTB',
            'latitude' => -8.653124,
            'longitude' => 116.200380,
        ],
        [
            'id' => 16,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kopang',
            'alamat' => 'Kopang, Lombok Tengah, NTB',
            'latitude' => -8.631720,
            'longitude' => 116.347142,
        ],
        [
            'id' => 17,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Praya Barat',
            'alamat' => 'Praya Barat, Lombok Tengah, NTB',
            'latitude' => -8.742034851410793,
            'longitude' => 116.24200641657487,
        ],
        [
            'id' => 18,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Pringgarata',
            'alamat' => 'Pringgarata, Lombok Tengah, NTB',
            'latitude' => -8.6189455,
            'longitude' => 116.2525291,
        ],

        // ================= LOMBOK TIMUR =================
        [
            'id' => 19,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Selong',
            'alamat' => 'Selong, Lombok Timur, NTB',
            'latitude' => -8.65010697928796,
            'longitude' => 116.53587279104221,
        ],
        [
            'id' => 20,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Montong Betok',
            'alamat' => 'Montong Betok, Lombok Timur, NTB',
            'latitude' => -8.5977326,
            'longitude' => 116.401330421,
        ],
        [
            'id' => 21,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Kotaraja',
            'alamat' => 'Kotaraja, Lombok Timur, NTB',
            'latitude' => -8.592443259199676,
            'longitude' => 116.42260464130234,
        ],
        [
            'id' => 22,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Paokmotong',
            'alamat' => 'Paokmotong, Lombok Timur, NTB',
            'latitude' => -8.6273252,
            'longitude' => 116.4577650,
        ],
        [
            'id' => 23,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Dasan Lekong',
            'alamat' => 'Dasan Lekong, Lombok Timur, NTB',
            'latitude' => -8.59830714076589,
            'longitude' => 116.52336947680963,
        ],
        [
            'id' => 24,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Aikmel',
            'alamat' => 'Aikmel, Lombok Timur, NTB',
            'latitude' => -8.568140,
            'longitude' => 116.532917,
        ],
        [
            'id' => 25,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Labuhan Lombok',
            'alamat' => 'Labuhan Lombok, Lombok Timur, NTB',
            'latitude' => -8.504950713963344,
            'longitude' => 116.66126824657722,
        ],
        [
            'id' => 26,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Sambelia',
            'alamat' => 'Sambelia, Lombok Timur, NTB',
            'latitude' => -8.3889390,
            'longitude' => 116.7138969,
        ],

        // ================= SUMBAWA =================
        [
            'id' => 27,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Taliwang',
            'alamat' => 'Taliwang, Sumbawa Barat, NTB',
            'latitude' => -8.744090,
            'longitude' => 116.847420,
        ],
        [
            'id' => 28,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Seteluk',
            'alamat' => 'Seteluk, Sumbawa Barat, NTB',
            'latitude' => -8.626904,
            'longitude' => 116.864308,
        ],
        [
            'id' => 29,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Sumbawa',
            'alamat' => 'Sumbawa Besar, NTB',
            'latitude' => -8.488132101223862,
            'longitude' => 117.41755017332956,
        ],
        [
            'id' => 30,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Empang',
            'alamat' => 'Empang, Sumbawa, NTB',
            'latitude' => -8.76889,
            'longitude' => 118.00286,
        ],
        [
            'id' => 31,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Plampang',
            'alamat' => 'Plampang, Sumbawa, NTB',
            'latitude' => -8.797363923089362,
            'longitude' => 117.77908755406888,
        ],
        [
            'id' => 32,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Lopok',
            'alamat' => 'Lopok, Sumbawa, NTB',
            'latitude' => -8.611778,
            'longitude' => 117.568306,
        ],
        [
            'id' => 33,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Moyo',
            'alamat' => 'Moyo, Sumbawa, NTB',
            'latitude' => -8.520937,
            'longitude' => 117.492830,
        ],
        [
            'id' => 34,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Lenangguar',
            'alamat' => 'Lenangguar, Sumbawa, NTB',
            'latitude' => -8.733434750717333,
            'longitude' => 117.36353479304607,
        ],
        [
            'id' => 35,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Labuhan Sumbawa',
            'alamat' => 'Labuhan Sumbawa, NTB',
            'latitude' => -8.470911,
            'longitude' => 117.399008,
        ],
        [
            'id' => 36,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Utan',
            'alamat' => 'Utan, Sumbawa, NTB',
            'latitude' => -8.4128625,
            'longitude' => 117.1345781,
        ],
        [
            'id' => 37,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Alas',
            'alamat' => 'Alas, Sumbawa, NTB',
            'latitude' => -8.5152082,
            'longitude' => 116.9938045,
        ],

        // ================= DOMPU & BIMA =================
        [
            'id' => 38,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Dompu',
            'alamat' => 'Dompu, NTB',
            'latitude' => -8.539311,
            'longitude' => 118.462102,
        ],
        [
            'id' => 39,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Montabaru',
            'alamat' => 'Montabaru, Dompu, NTB',
            'latitude' => -8.547335,
            'longitude' => 118.431802,
        ],
        [
            'id' => 40,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Soriutu',
            'alamat' => 'Soriutu, Dompu, NTB',
            'latitude' => -8.5190343,
            'longitude' => 118.3221665,
        ],
        [
            'id' => 41,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Rasabou',
            'alamat' => 'Rasabou, Bima, NTB',
            'latitude' => -8.739663,
            'longitude' => 118.437720,
        ],
        [
            'id' => 42,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Bima',
            'alamat' => 'Kota Bima, NTB',
            'latitude' => -8.453797,
            'longitude' => 118.724051,
        ],
        [
            'id' => 43,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Woha',
            'alamat' => 'Woha, Kabupaten Bima, NTB',
            'latitude' => -8.587800630949802,
            'longitude' => 118.69631872204275,
        ],
        [
            'id' => 44,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Bolo',
            'alamat' => 'Bolo, Kabupaten Bima, NTB',
            'latitude' => -8.505445972949396,
            'longitude' => 118.61859376306816,
        ],
        [
            'id' => 45,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Cabang Sape',
            'alamat' => 'Sape, Kabupaten Bima, NTB',
            'latitude' => -8.5745870,
            'longitude' => 118.9988758,
        ],

        // ================= KANTOR KAS =================
        [
            'id' => 46,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Bertais',
            'alamat' => 'Bertais, Kota Mataram, NTB',
            'latitude' => -8.5969642,
            'longitude' => 116.1550687,
        ],
        [
            'id' => 47,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Seketeng',
            'alamat' => 'Seketeng, Sumbawa, NTB',
            'latitude' => -8.507628,
            'longitude' => 117.428642,
        ],
        [
            'id' => 48,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Buer',
            'alamat' => 'Buer, Sumbawa, NTB',
            'latitude' => -8.462630,
            'longitude' => 117.040857,
        ],
        [
            'id' => 49,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Labuhan Jambu',
            'alamat' => 'Labuhan Jambu, Sumbawa, NTB',
            'latitude' => -8.696667,
            'longitude' => 118.019681,
        ],
        [
            'id' => 50,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Belo',
            'alamat' => 'Belo, Kabupaten Bima, NTB',
            'latitude' => -8.553612,
            'longitude' => 118.695286,
        ],
        [
            'id' => 51,
            'nama' => 'PT BPR NTB PERSERODA - Kantor Kas Bajo',
            'alamat' => 'Bajo, Kabupaten Bima, NTB',
            'latitude' => -8.455244585728883,
            'longitude' => 118.68376290294685,
        ],

    ],

];
